# Generated by Django 2.0.6 on 2018-09-04 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0005_auto_20180904_0728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('help_str', models.CharField(max_length=255, verbose_name='help text to help users filling the questionnaire')),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.Questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
