# Generated by Django 2.0.6 on 2018-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_questionnaire_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
