# Generated by Django 2.0.6 on 2018-09-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_auto_20180707_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='questionnaire',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
